### ISSUE TITLE
Profile Flask app running uwsgi

### ISSUE THREAD

**Issue by simkessy** [what-studio/profiling#61]
I have a docker container that runs uwsgi to lunch my flask app, how do I profile thing? I'd like to see performance of one of my routes that's slow. 

I tried: 

```
        environment:
            PYTHONPATH: ".:/code:/code/libs"
            FLASK_APP: "pinqueue"
            FLASK_DEBUG: "true"
            PINQUEUE_ENV: "development"
            USER: ${USER}
            TLS_ENABLED: "true"
        command: uwsgi --gevent 10 --gevent-monkey-patch --http-socket 0.0.0.0:10001 --http-websockets --module pinqueue:app --master --processes 4 --enable-threads --honour-stdin --py-autoreload=3 --buffer-size=65535
```
